version: '3'

services:
  wordpress_db:
    #Container do MYSQL
    image: mysql:5.7 #FROM mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./env/db.env
    networks:
      - backend

  wordpress:
    depends_on:
      - wordpress_db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./env/wordpress.env
    networks:
      - backend

volumes:
  db_data: {}
networks:
  backend:
