version: '3'

services:
  wordpress_db:
    #Container do MYSQL
    image: mysql:5.7 #FROM mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Mysql!2010'
      MYSQL_DATABASE: 'wordpress'

  wordpress:
    depends_on:
      - wordpress_db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: 'wordpress_db:3306'
      WORDPRESS_DB_NAME: 'wordpress'
      WORDPRESS_DB_USER: 'root'
      WORDPRESS_DB_PASSWORD: 'Mysql!2010'
volumes:
  db_data: {}
